accountapp/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from accountapp import views
from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete')
]

articleapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

projectapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from projectapp.views import ProjectCreateView, ProjectListView, ProjectDetailView

app_name = 'projectapp'

urlpatterns = [
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('list/', ProjectListView.as_view(), name='list'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),

]

repinterest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

subscribeapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body>
    {% include 'header.html' %}
    <hr>

    {% block content %}
    {% endblock %}
    <hr>

    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div style="text-align: center; margin-top: 2rem">
    <div style="font-size: .6rem">
        <span>공지사항</span>
        <span>제휴문의</span>
        <span>서비스센터</span>
    </div>
    <div class=pragmatic_logo style="margin-top: 1rem;">Pragmatic</div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <!-- 부트스트랩 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- 구글폰트 -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Hubballi&family=Nunito:wght@200&family=Sansita+Swashed:wght@300&family=Smooch+Sans:wght@100&display=swap"
          rel="stylesheet">

    <!-- GOOGLE MATERIAL ICONS -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">

    <!-- Default css link -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
</head>

templates/header.html
<div style="text-align: center">
    <div style="font-size: 3rem; text-decoration-line : none;" class="pragmatic_logo">
        <a href="{% url 'articleapp:list' %}">
            Pragmatic
        </a>

    </div>
    <div class="pragmatic_header_navebar">
        <a href="{% url 'articleapp:list' %}" class="a_design">
            <span>Articles</span>
        </a>
        <a href="{% url 'projectapp:list' %}" class="a_design">
            <span>Project</span>
        </a>
        <a href="{% url 'subscribeapp:list' %}" class="a_design">
            <span>Subscription</span>
        </a>

        {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="a_design">
                <span>login</span>
            </a>
            <a href="{% url 'accountapp:create' %}" class="a_design">
                <span>signup</span>
            </a>
        {% else %}
            <a href="{% url 'accountapp:detail' pk=user.pk %}" class="a_design">
                <span>mypage</span>
            </a>
            <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="a_design">
                <span>logout</span>
            </a>
        {% endif %}
    </div>
</div>